// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPGaLtgMOmByTiNxYKeAHizWkL_x_Br_g',
    appId: '1:928924996559:web:2f7b8dc7349fe1850cf8ba',
    messagingSenderId: '928924996559',
    projectId: 'wastey-c8593',
    authDomain: 'wastey-c8593.firebaseapp.com',
    storageBucket: 'wastey-c8593.appspot.com',
    measurementId: 'G-JP4DMK4Z91',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtDQ-KBCRpzEqlHD1zZQuday-pYP6wvAY',
    appId: '1:928924996559:android:6edc1af5eefa84ac0cf8ba',
    messagingSenderId: '928924996559',
    projectId: 'wastey-c8593',
    storageBucket: 'wastey-c8593.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnzKwG_tG2Pn61g5KhFw7WMjx90mUqg6c',
    appId: '1:928924996559:ios:4c3c05a979baabfd0cf8ba',
    messagingSenderId: '928924996559',
    projectId: 'wastey-c8593',
    storageBucket: 'wastey-c8593.appspot.com',
    iosClientId: '928924996559-6rn1hns2iiicdi904vtbt23stkjrfv6s.apps.googleusercontent.com',
    iosBundleId: 'no',
  );
}
